defaults: 
  - mode: default_2021




data_dir_relative_to_project_root: data
datafile: "2021-06-25-2021-06-30.nc"
model_save_dest: saved_models
test_indices: test_indices/2021_test_stratification.pt

copernicusmarine: 
  USERNAME: skostousov


epochs: 100
batch_size: 20
days: False
early_stopping_thresh: 10

features: [bottomT, so, thetao, uo, vo, zos, mlotst]