mode: daily_alternative_small
data_dir_relative_to_project_root: data
datafile: 1993-10-11-1993-10-12.nc
model_save_dest: saved_models
test_indices: test_indices/1993_test_stratification_larger_regions(10_img).pt
copernicusmarine:
  USERNAME: skostousov
epochs: 1000
batch_size: 20
days: false
early_stopping_thresh: 10
features:
- bottomT
- so
- thetao
- uo
- vo
- zos
- mlotst
daily_small:
  submode: small
  training:
    epochs: 100
    batch_size: 50
    early_stopping_thresh: 10
    model_save_dest: saved_models/saved_daily_small_models
    immediate_test: true
  eval:
    results_dir: results
  data:
    dataset_id: cmems_mod_glo_phy_my_0.083deg_P1D-m
    features:
    - bottomT
    - so
    - thetao
    - uo
    - vo
    - zos
    - mlotst
    data_dir: data/daily_small
    latitude_range:
    - 49
    - 61
    longitude_range:
    - -143
    - -130
    grid_size: 21
    small:
      start_date: 1993-01-01
      end_date: 1993-01-30
      output_file: small_daily_sample_1993-1993.nc
      test_indices: test_indices/daily_small/small_01.pt
      stats: stats/daily_small/small_01.pt
daily_alternative_small:
  submode: small
  training:
    epochs: 100
    batch_size: 50
    early_stopping_thresh: 10
    model_save_dest: saved_models/saved_daily_alternative_small_models
    immediate_test: true
  eval:
    results_dir: results
  data:
    dataset_id: cmems_mod_glo_phy_my_0.083deg_P1D-m
    features:
    - bottomT
    - so
    - thetao
    - uo
    - vo
    - zos
    - mlotst
    data_dir: data/daily_alternative_small
    latitude_range:
    - 47
    - 61
    longitude_range:
    - -152
    - -127
    grid_size: 21
    small:
      start_date: 1993-01-01
      end_date: 1993-01-30
      output_file: small_daily_alternative_sample_1993-1993.nc
      test_indices: test_indices/daily_alternative_small/small_01.pt
      stats: stats/daily_alternative_small/small_01.pt
daily:
  submode: very_small
  training:
    epochs: 1
    batch_size: 50
    early_stopping_thresh: 10
    model_save_dest: saved_models/saved_daily_models
    immediate_test: true
  eval:
    results_dir: results
  data:
    dataset_id: cmems_mod_glo_phy_my_0.083deg_P1D-m
    features:
    - bottomT
    - so
    - thetao
    - uo
    - vo
    - zos
    - mlotst
    data_dir: data/daily
    latitude_range:
    - 31
    - 61
    longitude_range:
    - -160
    - -120
    grid_size: 21
    small:
      start_date: 1993-01-01
      end_date: 1993-01-30
      output_file: small_daily_sample_1993-1994.nc
      test_indices: test_indices/daily/small_01.pt
      stats: stats/daily/small_01.pt
    very_small:
      start_date: 1993-01-01
      end_date: 1993-01-06
      output_file: very_small_daily_sample_1993-1994.nc
      test_indices: test_indices/daily/very_small_01.pt
      stats: stats/daily/very_small_01.pt
monthly:
  submode: large
  training:
    epochs: 1000
    batch_size: 50
    early_stopping_thresh: 10
    model_save_dest: saved_models/saved_monthly_models
    immediate_test: true
  eval:
    results_dir: results
  data:
    dataset_id: cmems_mod_glo_phy_my_0.083deg_P1M-m
    features:
    - bottomT
    - so
    - thetao
    - uo
    - vo
    - zos
    - mlotst
    data_dir: data/monthly
    latitude_range:
    - 31
    - 61
    longitude_range:
    - -160
    - -120
    grid_size: 21
    large:
      start_date: 1993-01-01
      end_date: 2021-06-01
      output_file: monthly_1993-2021.nc
      test_indices: test_indices/monthly/large_01.pt
      stats: stats/monthly/large_01.pt
    ten:
      start_date: 1993-01-01
      end_date: 2003-01-01
      output_file: ten_sample_1993-2003.nc
      test_indices: test_indices/monthly/ten_01.pt
      stats: stats/monthly/ten_01.pt
    medium:
      start_date: 1993-01-01
      end_date: 2010-01-01
      output_file: medium_sample_1993-2010.nc
      test_indices: test_indices/monthly/medium_01.pt
      stats: stats/monthly/medium_01.pt
    small:
      start_date: 1993-01-01
      end_date: 1994-01-01
      output_file: small_sample_1993-1994.nc
      test_indices: test_indices/monthly/small_01.pt
      stats: stats/monthly/small_02.pt
project_root: /mnt/c/Users/samue/SynologyDrive/OceanPropInfSatImg
